'use client'

import { useState } from 'react'
import { ArrowUpRight, Menu, X } from 'lucide-react'

const capabilities = [
  ['01', 'NATURAL-LANGUAGE QUERYING', 'Ask questions in plain language and begin with the objective, not a search term.'],
  ['02', 'EVIDENCE RETRIEVAL', 'Gather source material, dates and entities into a traceable evidence base.'],
  ['03', 'RELATIONSHIP IDENTIFICATION', 'Surface connections between people, institutions, policies, markets and events.'],
  ['04', 'ANALYTICAL REPORTING', 'Turn validated relationships into a clearer picture for action.'],
]
const audience = ['BUILDERS', 'RESEARCHERS', 'INFORMATION HOLDERS', 'INDUSTRY EXPERTS', 'EARLY USERS', 'PARTNERS', 'CURIOUS PEOPLE']
const journey = [['TODAY', 'FOUNDATION'], ['NEXT', 'RELATIONSHIPS'], ['THEN', 'INTELLIGENCE'], ['BEYOND', 'AFRICA']]

function Label({ children }: { children: React.ReactNode }) { return <p className="sys-label"><span />{children}</p> }
function Section({ id, label, children, tone = 'paper' }: { id?: string; label: string; children: React.ReactNode; tone?: 'paper' | 'dark' | 'quiet' }) { return <section id={id} className={`sys-section tone-${tone}`}><div className="sys-grid"><Label>{label}</Label>{children}</div></section> }
function Diagram({ type }: { type: 'fragment' | 'architecture' | 'pipeline' | 'loop' | 'network' | 'provenance' }) {
  const maps = { fragment: ['POLICY', 'MINISTRY', 'COMPANY', 'PROGRAM', 'REPORT', 'REGULATION', 'DATASET', 'ONE STORY'], architecture: ['PEOPLE', 'INSTITUTIONS', 'RESEARCHERS', 'ORGANIZATIONS', 'ATIS', 'RITA', 'EVIDENCE', 'INTELLIGENCE'], pipeline: ['SIGNALS', 'SOURCE', 'EVIDENCE', 'CONTEXT', 'RELATIONSHIPS', 'RITA', 'STORY', 'ACTION'], loop: ['EVIDENCE', 'SEMANTIC EXTRACTION', 'TYPED RELATIONSHIPS', 'TRIAGE', 'STORY GRAPH', 'DISCOVERY', 'VALIDATION', 'ACTION'], network: ['BUILDERS', 'RESEARCHERS', 'EXPERTS', 'INFORMATION HOLDERS', 'INSTITUTIONS', 'PARTNERS'], provenance: ['STORY', 'RELATIONSHIP', 'EVIDENCE', 'SOURCE'] }
  return <div className={`system-diagram diagram-${type}`} role="img" aria-label={`${type} system diagram`}><div className="diagram-lines" aria-hidden="true" /><div className="diagram-core">{type === 'architecture' ? 'AKSOS' : type === 'network' ? 'AKSOS' : type === 'provenance' ? 'TRACEABLE' : type === 'fragment' ? 'ONE STORY' : 'INTELLIGENCE'}</div>{maps[type].map((item, i) => <span key={item} style={{ ['--i' as string]: i }}>{item}</span>)}</div>
}
function Hero() { return <section className="sys-hero"><div className="sys-grid"><div className="hero-copy"><Label>AKSOS / INTELLIGENCE INFRASTRUCTURE</Label><h1>Building intelligence infrastructure <em>for Africa.</em></h1><p>Africa already produces enormous amounts of information. The harder problem is understanding how it connects.</p><div className="link-row"><a className="primary-link" href="#connect">Start a conversation <ArrowUpRight /></a><a href="https://atis.aksos.net">Explore ATIS <ArrowUpRight /></a></div></div><Diagram type="fragment" /></div></section> }
function Approach() { return <Section id="approach" label="03 / THE AKSOS APPROACH"><h2>Technology is only part of the infrastructure.</h2><p className="section-lede">Meaningful intelligence requires both the system and the network around it.</p><Diagram type="architecture" /></Section> }
function Atis() { return <Section id="atis" label="04 / THE SYSTEM" tone="dark"><h2>ATIS</h2><p className="section-lede">An intelligence platform we&apos;re building to connect evidence, relationships and emerging information.</p><div className="atis-reveal"><div><span>QUESTION</span><strong>What connects this policy to current opportunity?</strong></div><div><span>EVIDENCE → RELATIONSHIPS → CONTEXT</span><strong>Analysis assembled from traceable source material.</strong></div><div><span>REPORT</span><strong>A clearer picture for action.</strong></div></div></Section> }
function Pipeline() { return <Section label="05 / HOW INFORMATION BECOMES INTELLIGENCE"><h2>Better signals. Clearer understanding.</h2><p className="section-lede">Each stage adds structure, context and traceability.</p><Diagram type="pipeline" /></Section> }
function Capabilities() { return <Section label="06 / CURRENT CAPABILITIES" tone="quiet"><h2>What exists today.</h2><div className="capability-index">{capabilities.map(([n, title, copy]) => <div key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></Section> }
function Rita() { return <Section id="rita" label="06 / RITA IN ACTION" tone="dark"><h2>From fragmented evidence to <em>actionable intelligence.</em></h2><p className="section-lede">RITA reveals which relationships around an event are meaningful enough to change what it means.</p><div className="investigation"><span>SOURCE</span><b>EVENT</b><b>ENTITY</b><b>RELATIONSHIP</b><b>CONTEXT</b><strong>STORY → INTELLIGENCE</strong></div></Section> }
function Trust() { return <Section label="08 / PROVENANCE & TRUST"><h2>If we can&apos;t trace it, we don&apos;t know enough.</h2><Diagram type="provenance" /></Section> }
function Status() { return <Section label="09 / HONEST STATUS" tone="quiet"><h2>We&apos;re still building.</h2><div className="status-list">{[['ATIS','EXPERIMENTAL'],['RITA','DEVELOPING'],['NETWORK','BUILDING'],['INTELLIGENCE MODEL','EVOLVING']].map(([a,b]) => <div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></Section> }
function People() { return <Section label="10 / THE NETWORK"><h2>We&apos;re building the network, too.</h2><Diagram type="network" /></Section> }
function Invitation() { return <Section label="11 / WHO SHOULD BE PART OF THIS?" tone="quiet"><h2>People close to the information.</h2><div className="audience-index">{audience.map((item, i) => <div key={item}><span>0{i + 1}</span><strong>{item}</strong><p>Contribute perspective, access, evidence or relationships.</p></div>)}</div></Section> }
function Journey() { return <Section id="journey" label="12 / THE JOURNEY"><h2>Zimbabwe <em>→</em> Africa</h2><div className="journey-line">{journey.map(([when, what]) => <div key={when}><span>{when}</span><strong>{what}</strong></div>)}</div></Section> }
function Final() { return <section id="connect" className="final-statement"><Label>13 / THE NEXT STAGE</Label><h2>We&apos;re not finished.<br /><em>That&apos;s the point.</em></h2><p>We are building the systems and relationships needed to understand how information connects.</p><a className="primary-link" href="mailto:hello@aksos.net">Start a conversation <ArrowUpRight /></a></section> }

export function AksosSite() { const [open, setOpen] = useState(false); return <main><header className="site-header"><a href="#top" className="wordmark">AKSOS</a><nav className={open ? 'nav-open' : ''}><a href="#approach">Approach</a><a href="#atis">ATIS</a><a href="/batana">Batana</a><a href="#rita">RITA</a><a href="#journey">Journey</a><a href="#connect">Start a conversation →</a></nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X /> : <Menu />}</button></header><div id="top"><Hero /></div><Section id="why" label="01 / THE PROBLEM"><h2>The information is there.</h2><p className="section-lede">Governments publish policies. Organizations launch programs. Companies enter markets. The information exists, but it rarely arrives as one coherent picture.</p><Diagram type="fragment" /></Section><Section label="02 / WHAT WE LEARNED" tone="quiet"><h2>The internet is not the whole picture.</h2><p className="section-lede">Better intelligence does not begin with a better answer. It begins with better evidence.</p><div className="vertical-flow">PUBLIC INFORMATION ↓ MISSING CONTEXT ↓ PEOPLE ↓ INSTITUTIONS ↓ FIRST-SOURCE KNOWLEDGE</div></Section><Approach /><Atis /><Section label="04A / THE NETWORK" tone="dark"><h2>Information doesn&apos;t always live in databases. Sometimes, it lives in people.</h2><p className="section-lede">Batana helps find relevant people and organizations when conventional search cannot.</p><Diagram type="network" /><a className="primary-link" href="/batana">Explore Batana <ArrowUpRight /></a></Section><Pipeline /><Capabilities /><Rita /><Section label="07 / THE INTELLIGENCE LOOP"><h2>Evidence becomes understanding through relationships.</h2><Diagram type="loop" /></Section><Trust /><Status /><People /><Invitation /><Journey /><Final /><footer><span>AKSOS</span><p>The information is already there. We&apos;re building the systems and relationships needed to understand how it connects.</p><small>Harare · Zimbabwe / 2026</small></footer></main> }
export default AksosSite
