'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Menu, X } from 'lucide-react'

const needs = ['Investment opportunities', 'Funding opportunities', 'Local partners', 'Organizations', 'Businesses', 'Government / institutional contacts', 'Specialists / expertise', 'Projects', 'Market information', 'Regulatory information', 'Other']
const stages = [
  ['01', 'VISION', 'What are you trying to accomplish?'],
  ['02', 'CONTEXT', 'What are you trying to build, fund, invest in, research, or change?'],
  ['03', 'REQUIREMENTS', 'What people, capabilities, information, resources, or relationships are missing?'],
  ['04', 'DISCOVERY', 'Where might those capabilities or relationships exist?'],
  ['05', 'VALIDATION', 'Does the potential match actually fit what you need?'],
  ['06', 'CONNECTION', 'Where there is a genuine fit, we help create the introduction.'],
]

function Label({ children }: { children: React.ReactNode }) { return <p className="section-label"><span className="label-rule" />{children}</p> }

export function BatanaPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedNeeds, setSelectedNeeds] = useState<string[]>([])
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState('')
  const toggle = (value: string) => setSelectedNeeds((items) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value])
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedNeeds.length) { setError('Please select at least one thing you need help finding.'); return }; setError(''); setSubmitted(true) }
  return <main className="batana-page" id="top">
    <header className="site-header batana-header"><a href="/#top" className="wordmark"><img className="brand-mark brand-mark-small" src="/aksos-symbol-traced.svg" alt="" /><span>AKSOS</span></a><nav className={menuOpen ? 'nav-open' : ''} aria-label="Main navigation"><a href="/#why" onClick={() => setMenuOpen(false)}>Why we&apos;re building</a><a href="/#atis" onClick={() => setMenuOpen(false)}>ATIS</a><a href="/batana" onClick={() => setMenuOpen(false)}>Batana</a><a href="#apply" onClick={() => setMenuOpen(false)}>Apply</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close navigation' : 'Open navigation'}>{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="batana-hero-v2"><div className="batana-hero-overlay" /><div className="batana-hero-copy"><p className="eyebrow">PROJECT BATANA</p><h1>You know what you want to do in Zimbabwe.<br /><em>But you may not know who can help you do it.</em></h1><div className="batana-hero-body"><p>You can spend weeks searching Google, reading reports, sending emails, and asking people you already know. And still not find the person, organization, company, or institution you actually need.</p><p>But you don&apos;t need to know who to talk to before you start.</p><p>Tell us what you&apos;re trying to accomplish. We&apos;ll work to understand your objective and connect you with viable people and partners who match what you want to achieve.</p></div><div className="hero-actions"><a className="button button-solid" href="#apply">Apply for a pilot slot <ArrowDown /></a><a className="button button-quiet" href="#how">See how it works</a></div></div><div className="batana-hero-index">EARLY PILOT<br /><span>OBJECTIVE → CONNECTION</span></div></section>
    <section className="batana-chapter"><Label>01 / THE PROBLEM</Label><h2>The information you need may not be online.</h2><div className="batana-copy"><p>You can find thousands of pages about Zimbabwe. But that doesn&apos;t mean you&apos;ll find the person who can actually help you.</p><p>The information you need may be spread across ministries, companies, local organizations, professional networks, reports, websites, or people who simply aren&apos;t visible through a normal search.</p><p>Sometimes the problem isn&apos;t that the information doesn&apos;t exist. It&apos;s that you don&apos;t know where it lives — or who holds it.</p></div><p className="batana-callout">But you don&apos;t need to map Zimbabwe before you can start.<br /><em>You need to tell us what you&apos;re trying to accomplish.</em></p></section>
    <section className="batana-flow"><Label>02 / SEARCHING VS FINDING</Label><h2>The visitor starts with an objective,<br /><em>not with a contact list.</em></h2><div className="flow-diagram"><div className="flow-track searching"><h3>SEARCHING ALONE</h3>{['Your objective', 'Google', 'Reports', 'Websites', 'Emails', 'Cold introductions', 'Unknown information'].map((item) => <div className="flow-node" key={item}>{item}<span>↓</span></div>)}<strong>“Who actually knows?”</strong></div><div className="flow-divider">OR</div><div className="flow-track finding"><h3>PROJECT BATANA</h3>{['Your objective', 'Understand what you need', 'Identify relevant people & organizations', 'Investigate potential matches', 'Assess relevance', 'Find the right connection'].map((item) => <div className="flow-node" key={item}>{item}<span>↓</span></div>)}<strong>Conversation</strong></div></div></section>
    <section className="batana-chapter objective"><Label>03 / YOUR OBJECTIVE</Label><h2>Start with your vision.<br /><em>Not your search history.</em></h2><div className="batana-copy"><p>You might already know exactly what you want to do. You may want to invest. Fund a project. Build a company. Find a local partner. Expand an organization. Research a market. Or turn an idea into something real.</p><p>The difficult part may be everything you don&apos;t know yet: who has the expertise, relationships, local capacity, or relevant information.</p></div><div className="objective-list">{['I want to invest in Zimbabwe.', 'I want to fund a high-impact project.', 'I want to build something.', 'I want to find a local implementation partner.', 'I want to expand an existing organization.', 'I have an idea, but I don&apos;t know who could make it possible.'].map((item) => <p key={item}>{item}</p>)}</div><p className="batana-callout">Your objective is the starting point.</p></section>
    <section className="batana-dark-v2" id="how"><Label>04 / HOW BATANA WORKS</Label><h2>We do not start by searching for random people.</h2><p className="wide-copy">We start by understanding what you are trying to accomplish. Then we move through context, requirements, discovery, validation, and connection.</p><div className="batana-process-v2">{stages.map(([number, title, copy], i) => <div className={i === 0 ? 'process-node first' : 'process-node'} key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p>{i < stages.length - 1 && <b>↓</b>}</div>)}</div><p className="batana-outcome">The outcome may be a conversation, a partnership, a project, an investment, or a new relationship. We do not promise the final outcome.</p></section>
    <section className="batana-chapter difference"><Label>05 / THE DIFFERENCE</Label><h2>We don&apos;t just give you a list of names.</h2><div className="batana-copy"><p>Finding a name on Google is easy. Finding someone who actually fits your objective is harder.</p><p>A useful connection isn&apos;t simply someone who works in your sector. It is someone whose capabilities, position, experience, resources, location, or relationships make sense for what you are actually trying to accomplish.</p></div><div className="match-diagram"><div><span>YOUR OBJECTIVE</span><b>What you want to accomplish</b></div><i>→</i><div><span>WHAT YOU NEED</span><b>Capital · Expertise · Local knowledge · Implementation · Relationships</b></div><i>→</i><div><span>FIT</span><b>Relevant? Credible? Capable? Aligned?</b></div><i>→</i><div className="match-result"><span>CONNECTION</span><b>A relevant conversation</b></div></div><p className="batana-callout">The objective isn&apos;t to give you more names.<br /><em>It&apos;s to help you find the right people to talk to.</em></p></section>
    <section className="batana-pilot"><div><Label>06 / PROJECT BATANA</Label><h2>We don&apos;t want everyone.</h2><p>Project Batana is not for people who are simply curious about Zimbabwe. This pilot is for people who want to do something.</p><div className="verb-list">Invest. · Fund. · Build. · Expand. · Partner. · Research. · Create. · Solve.</div></div><div className="pilot-note"><strong>We need this to work.</strong><p>The pilot only proves its value if people move from an idea to a conversation, from a conversation to a relationship, and from a relationship to something real.</p></div></section>
    <section className="batana-apply-v2" id="apply"><div className="apply-copy"><Label>07 / APPLY</Label><h2>Tell us what you&apos;re trying to accomplish.</h2><p>You don&apos;t need to know who you need to talk to. You just need to know what you want to make happen.</p></div><form className="batana-form" onSubmit={submit}><div className="form-grid"><label>FULL NAME<input required name="name" /></label><label>ORGANIZATION<input name="organization" /></label><label>EMAIL<input required type="email" name="email" /></label><label>COUNTRY<input name="country" /></label></div><label>WHAT ARE YOU TRYING TO ACCOMPLISH IN ZIMBABWE?<textarea required rows={4} name="objective" /></label><label>WHAT IS YOUR VISION?<textarea required rows={4} name="vision" /></label><label>HOW DO YOU INTEND TO ACCOMPLISH IT?<textarea rows={4} name="approach" /></label><fieldset><legend>WHAT DO YOU NEED HELP FINDING?</legend><div className="batana-checks">{needs.map((need) => <label key={need}><input type="checkbox" checked={selectedNeeds.includes(need)} onChange={() => toggle(need)} /><span>{selectedNeeds.includes(need) && <Check />}</span>{need}</label>)}</div></fieldset><label>WHAT KIND OF PARTNER ARE YOU LOOKING FOR?<input name="partner" /></label><div className="form-grid"><label>SECTOR<input name="sector" /></label><label>TIMELINE<select name="timeline" defaultValue=""><option value="" disabled>Select one</option><option>Exploring</option><option>Within 3 months</option><option>3–6 months</option><option>6–12 months</option><option>12+ months</option></select></label></div><label>APPROXIMATE INVESTMENT OR FUNDING RANGE <small>(OPTIONAL)</small><input name="funding" /></label><label>WHAT WOULD NEED TO HAPPEN FOR YOU TO SERIOUSLY MOVE FORWARD?<textarea rows={4} name="move" /></label><fieldset><legend>IF WE IDENTIFY A STRONG MATCH, WOULD YOU BE OPEN TO AN INTRODUCTION?</legend><div className="radio-row"><label><input required type="radio" name="introduction" value="yes" /> Yes</label><label><input type="radio" name="introduction" value="no" /> No</label></div></fieldset>{error && <p className="form-error">{error}</p>}{submitted ? <div className="form-success"><Check />Application received. We&apos;ll review your objective carefully.</div> : <button className="button button-solid" type="submit">Apply for a pilot slot <ArrowUpRight /></button>}<p className="form-note">We review applications based on seriousness of intent, clarity of objective, and potential for a meaningful match.</p></form></section>
    <section className="batana-final-v2"><p className="eyebrow">PROJECT BATANA</p><h2>Your idea is only the beginning.</h2><p>You may already know exactly what you want to do. But the right people may still be missing.</p><a className="button button-solid" href="#apply">Apply for a Project Batana pilot slot <ArrowUpRight /></a><p className="final-motto">Real intentions. Real relationships. Real possibilities.</p></section><footer><p>AKSOS / <em>Building intelligence infrastructure for Africa.</em></p><p className="footer-meta">Project Batana · Early pilot</p></footer>
  </main>
}

export default BatanaPage
