'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Menu, X } from 'lucide-react'

const needs = ['Finding a partner', 'Research or analysis', 'Access to local context', 'A technical or implementation capability', 'Introductions or relationships', 'A route into a new sector or market']
const sectors = ['Energy', 'Agriculture', 'Finance', 'Technology', 'Healthcare', 'Infrastructure', 'Education', 'Other']

export function BatanaPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedNeeds, setSelectedNeeds] = useState<string[]>([])
  const [submitted, setSubmitted] = useState(false)
  const [formError, setFormError] = useState('')
  const toggleNeed = (need: string) => setSelectedNeeds((current) => current.includes(need) ? current.filter((item) => item !== need) : [...current, need])
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedNeeds.length) { setFormError('Select at least one way this pilot could help.'); return }; setFormError(''); setSubmitted(true) }
  return <main className="batana-page" id="top">
    <header className="site-header batana-header"><a href="/#top" className="wordmark"><img className="brand-mark brand-mark-small" src="/aksos-symbol-traced.svg" alt="" /><span>AKSOS</span></a><nav className={menuOpen ? 'nav-open' : ''} aria-label="Main navigation"><a href="/#why" onClick={() => setMenuOpen(false)}>Why we&apos;re building</a><a href="/#atis" onClick={() => setMenuOpen(false)}>ATIS</a><a href="/#rita-redesign" onClick={() => setMenuOpen(false)}>RITA</a><a href="#apply" onClick={() => setMenuOpen(false)}>Apply for pilot</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close navigation' : 'Open navigation'}>{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="batana-hero"><div className="batana-hero-copy"><p className="eyebrow">PROJECT BATANA / EARLY PILOT</p><h1>There are people trying to do serious things in Zimbabwe.</h1><p className="batana-deck">The challenge is often not ambition. It is finding the right connection.</p><a className="button button-solid" href="#apply">Tell us what you&apos;re trying to do <ArrowDown /></a></div><div className="batana-hero-image"><img src="/batana-hero.jpg" alt="Collaborators working together around a table" /><span>Project Batana / A connection infrastructure pilot</span></div></section>
    <section className="batana-intro"><p className="section-label"><span className="label-rule" />01 / THE PREMISE</p><h2>Some objectives are too important to leave to chance.</h2><div className="batana-two-col"><p>People arrive with serious objectives. Build something useful. Solve a difficult problem. Enter a sector. Find a partner. Understand a market. Make something work in Zimbabwe.</p><p>But the path from intention to progress is often unclear. The right person may be difficult to find. The relevant context may not be visible. A promising connection may never happen.</p></div></section>
    <section className="batana-dark"><div><p className="section-label">02 / WHAT BATANA IS TESTING</p><h2>What if the right introduction could change the outcome?</h2></div><div className="batana-wire"><div className="wire-label">OBJECTIVE</div><div className="wire-line" /><div className="wire-center">BATANA</div><div className="wire-line" /><div className="wire-label">VIABLE CONNECTION</div><div className="wire-note">Not a directory.<br />A considered route<br />through context.</div></div><p className="batana-large-note">Batana is an early pilot exploring how people, knowledge and opportunity can be connected more deliberately.</p></section>
    <section className="batana-sections"><p className="section-label">03 / THE QUESTION</p><h2>What are you trying to do?</h2><div className="batana-question-grid">{['Build or launch something', 'Find a partner or capability', 'Understand a sector or market', 'Solve a specific problem'].map((item, i) => <div key={item}><span>0{i + 1}</span><b>{item}</b><p>We want to understand the objective behind the request, not just the category it fits into.</p></div>)}</div></section>
    <section className="batana-image-break"><img src="/batana-hero.jpg" alt="People sharing context and ideas in conversation" /><div><p className="section-label">04 / THE EARLY PILOT</p><h2>We are looking for a small number of serious objectives.</h2><p>This is not a general networking service. It is a selective pilot for people with a clear objective and a willingness to explore what a useful connection might look like.</p><a className="text-link" href="#apply">Apply to participate <ArrowUpRight /></a></div></section>
    <section className="batana-steps"><p className="section-label">05 / HOW IT WORKS</p><h2>A simple beginning.</h2><div className="batana-process">{[['01','Tell us the objective','Share what you are trying to do, what is blocking progress and what kind of help may matter.'],['02','We look for the shape of the problem','We review the context and identify where a useful relationship, insight or route might exist.'],['03','We make a considered introduction','If there is a credible fit, we make the connection and learn from what happens next.']].map(([number,title,body]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className="batana-apply" id="apply"><div className="batana-apply-head"><p className="section-label">06 / PILOT APPLICATION</p><h2>Tell us what you&apos;re trying to do.</h2><p>This is an early pilot. We will review each submission carefully and follow up where there may be a useful fit.</p></div><form onSubmit={submit} className="batana-form"><label>YOUR NAME<input name="name" required placeholder="Full name" /></label><label>EMAIL ADDRESS<input name="email" type="email" required placeholder="you@example.com" /></label><label>ORGANISATION / PROJECT<input name="organisation" placeholder="Optional" /></label><label>WHAT ARE YOU TRYING TO DO?<textarea name="objective" required placeholder="Tell us about the objective in your own words." rows={5} /></label><fieldset><legend>WHAT WOULD HELP? <small>Select all that apply</small></legend><div className="batana-checks">{needs.map((need) => <label key={need}><input type="checkbox" checked={selectedNeeds.includes(need)} onChange={() => toggleNeed(need)} /><span>{selectedNeeds.includes(need) ? <Check /> : null}</span>{need}</label>)}</div></fieldset><label>RELEVANT SECTOR<select name="sector" defaultValue=""><option value="" disabled>Select a sector</option>{sectors.map((sector) => <option key={sector}>{sector}</option>)}</select></label><label>WHEN ARE YOU TRYING TO MOVE?<select name="timeline" defaultValue=""><option value="" disabled>Select a timeframe</option><option>Now / already underway</option><option>In the next 3 months</option><option>In the next 6 months</option><option>Exploring</option></select></label><label>ANYTHING ELSE WE SHOULD KNOW?<textarea name="context" placeholder="Context, constraints, or a useful introduction." rows={4} /></label>{formError && <p className="form-error">{formError}</p>}{submitted ? <div className="form-success"><Check />Thank you. We&apos;ll review your objective and be in touch if there is a useful next step.</div> : <button className="button button-solid" type="submit">Submit pilot application <ArrowUpRight /></button>}<p className="fine-print">We are reviewing early applications selectively. Submitting this form does not guarantee an introduction.</p></form></section>
    <section className="batana-final"><p className="eyebrow">PROJECT BATANA / A SMALL BEGINNING</p><h2>Serious objectives deserve better routes.</h2><a className="button button-solid" href="#apply">Start with the objective <ArrowUpRight /></a></section><footer><p>AKSOS / <em>Building intelligence infrastructure for Africa.</em></p><p className="footer-meta">Project Batana · Early pilot</p></footer>
  </main>
}
